name: newsboat
version: git
base: core18
summary: An RSS/Atom feed reader for text terminals
description: |
  Newsboat is an RSS/Atom feed reader for the text console. It's an actively
  maintained fork of Newsbeuter.
grade: stable
confinement: strict

apps:
  newsboat:
    command: usr/local/bin/newsboat
    environment:
      LOCPATH: "$SNAP/usr/lib/locale"
    plugs:
      - network
      - home
      - desktop
  podboat:
    command: usr/local/bin/podboat
    environment:
      LOCPATH: "$SNAP/usr/lib/locale"
    plugs:
      - network
      - home
      - desktop

parts:
  rust:
    plugin: nil
    build-snaps:
      - rustup
    override-build: |
      rustup install stable
  newsboat:
    after:
      - rust
    plugin: make
    source: .
    build-packages: 
      - pkg-config
      - libsqlite3-dev
      - libcurl4-openssl-dev
      - libxml2-dev
      - libstfl-dev
      - libjson-c-dev
      - libncursesw5-dev
      - asciidoctor
      - libssl-dev
      - gettext
      - g++
    stage-packages:
      - libxml2
      - librtmp1
      - locales-all
      - libcurl4
      - libstfl0
